### ISSUE TITLE
 Todo list

### ISSUE THREAD

**Issue by btzr-io** [butterproject/butter-style-guide#3]
### Todo

- [x] - Improve css animations
   - [x] -- Add dropdown animations
   - [x] -- Add autocomplete animations
- [x] - Improve search / autocomplete
- [x] - Add header
   - [x] -- Add icons
   - [x] -- Fix nav / dropdowns js
   - [x] -- Fix header css js
- [x] - Fix Dropdowns css
- [x] - Add Generic popup
- [x] - Add Dropups
- [x] - Debounce resize event
- [x] - Add Dropdowns
- [x] - Row for settings
- [x] - Selects
### Stand-by
- [ ]  - Player redesign

**Comment by SrPatinhas** [comment]
@btzr-io im taking care of it XD

**Comment by abadfederico** [comment]
- Row for settings
- Selects

**Comment by btzr-io** [comment]
@abadfederico what selects?
