### ISSUE TITLE
Player redesign

### ISSUE THREAD

**Issue by btzr-io** [butterproject/butter-style-guide#4]
### Todo
- [ ] - Add file / stream info
- [ ] - Add "Rate this movie" popup
- [ ] - Add "Rate this subtitle" popup
- [ ] - Add back button
### Stand-by
- [ ] - Add volume dropdown
- [ ] - Add subtitles dropdown
- [ ] - Update video.js skin  ? **Not** approved :(
